// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtjowrewuuhmnvmuilcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0am93cmV3dXVobW52bXVpbGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjQzOTksImV4cCI6MjA2MTI0MDM5OX0.zedLAq8nxRDv6AEdqRlEwOSwVaeu_FT8ixu4Za3ikuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);